### ISSUE TITLE
Create new API for accepting json, and submit to tangle as it is

### ISSUE THREAD

**Issue by feng-lu-veracity** [veracity/DataLineage-Viewer#10]
Create a new API for accepting json, verify its format. If format is ok, then submit to the tangle as it is. Do not modify the json content.

Before implement the functionality, please create swagger definition for reviewing. 

new API 
path: /api/publish
verb: POST

**Comment by feng-lu-veracity** [comment]
Verify the format against the json that i have updated in http://fenglu.me/2018/04/16/Data-integrity-and-data-lineage-by-using-IOTA/

We only verify the mandatory fields. Note that timestamp is not longer a mandatory field.

**Comment by cbfrank** [comment]
@feng-lu-veracity I have created a api-publish branch and committed the updated swagger json with the new api, please help to review.
To fix the swagger schema error, I made some changes to the existing schema.

**Comment by feng-lu-veracity** [comment]
@cbfrank i have updated the definition in swagger, but there is no implementation yet. Note that i decided to use a new schema, please check it in swagger UI. 

We need to implement the new API, but also update the existing simulator APIs to use the new format. I will also update the paper

**Comment by feng-lu-veracity** [comment]
@cbfrank the blog is updated with the new format. http://fenglu.me/2018/04/16/Data-integrity-and-data-lineage-by-using-IOTA/
Now we only have one format that covers the old 2 formats, see both from the blog and also the new definition from swagger.

{	
    datapackageId: string,	
    wayofProof:string,	
    valueOfProof:string,
    inputs...
}

Please continue your work on branch https://github.com/veracity/DataLineage-Viewer/tree/add-publish-api-new 

Note that we need to 
1. implement the publish api, and
2. convert the current simulate api to use the new format. 

the publish api and simulate api should use the same code base.

no update to the READ apis.

**Comment by cbfrank** [comment]
@feng-lu-veracity The publish api has been finished and the swagger.json is updated alos. I not only add and update the publish api swagger.json but alos fix all the schema errors of swagger.json
