### ISSUE TITLE
Refactoring simulate api

### ISSUE THREAD

**Issue by feng-lu-veracity** [veracity/DataLineage-Viewer#13]
Today the simulate api and publish api are using the same IOTAwriter code for sending data to tangle. There are duplicate code.

We need to refactor the simulate api, that it ONLY accepts client requests and create the correct json in server side memory, then call the publish API. 

publish API should be the ONLY endpoint for sending data to tangle.

**Comment by cbfrank** [comment]
@feng-lu-veracity the refactor code has been committed, 36f1159e, in this commit, the simulate web api is removed and will use the publish api to submit the data

**Comment by cbfrank** [comment]
@feng-lu-veracity as the https://nodes.iota.fm is very slow (from china at least), so when tested with swagger, you may get the error as the timeout, and swagger shows "fetch error", but the server side really save the package to iota after a while, you can open the chrome developer tool, and if the error is of status 0, then this is time out error not the real error when save data to iota
