### ISSUE TITLE
Introduce validation on publish API

### ISSUE THREAD

**Issue by feng-lu-veracity** [veracity/DataLineage-Viewer#15]
Today the publish API is check seed and mandatory fields of the request. but it does not check "ascii only" logic, as we are doing in the simulator web interface.

We need to make sure that the API checks ascii as well before it calls the IOTAWriter. If the request contains illegal char, return 400 bad request

**Comment by cbfrank** [comment]
@feng-lu-veracity the validation is added in the branch fetch-multi-data-check, related commits are ac4fe9d2 and e6046314

**Comment by cbfrank** [comment]
@feng-lu-veracity the rename changes has been committed 45220610
