### ISSUE TITLE
Need to drop IOTAProvider field from IOTAWriter cache

### ISSUE THREAD

**Issue by feng-lu-veracity** [veracity/DataLineage-Viewer#21]
PROBLEM:
Today the iota provider is a part of the cached iotawriter object. The provider (node url) is stored in data/iotaWriter.cache. 

Store this field makes it difficult to switch from an offline provider to a good one, as the code will still use the cached (offline) provider url when create a IOTAwriter. 

Today if we wanna switch from one provider to another one, he must:
1.  override the value in data/server-config file
2. stop the app for removing/updating the iotaWriter.cache file
3. either remove the iotaWriter.cache file or update all fields to use the good node.

SOLUTION:
We should not store the provider url as a part of the cached iota writer. When create a IOTAWriter instance, we ALWAYS apply the current IOTA provider url to the writer objects.

@frank-cb @cbfrank  pls help to fix.

**Comment by feng-lu-veracity** [comment]
btw, both our node and https://nodes.thetangle.org:443 have problems, but the original code is fine, except above issue, which was identified during the test.

Temporarily i switched datalineage-viewer.azurewebsites.net to a public node , and it is back to working now.

**Comment by frank-cb** [comment]
@feng-lu-veracity The pull request [https://github.com/veracity/DataLineage-Viewer/pull/22](url) is created to fix this bug. Please help to reivew.
The IOTAWriter use iota client internally, and the iota client is created with the iota provider url settings, so after the client is created, we can't change its iota provider url. The IOTAWriter also cache the MamState generated by iota client I'm not sure if this state should be match the iota provider url.
It's hard to reuse the iota client and mam state by just change the iota provider url, so to make it simple, I change the writer cache, which will first get the writer by seed, and then compare the writer iota provider url with the server-config provider url, if not same, then just drop the entire writer and create a new one.

**Comment by feng-lu-veracity** [comment]
Merged fix
