### ISSUE TITLE
Return 404 if data is not found

### ISSUE THREAD

**Issue by feng-lu-veracity** [veracity/DataLineage-Viewer#8]
In "get" APIs
- /address/{address}/{all}
- /address/channel/{rootAddress}
If the data is not found, e.g. provided a wrong address, the API should return status code 404, instead of status code 200 but an empty result.

Both the code and swagger should be updated

**Comment by cbfrank** [comment]
@feng-lu-veracity The address api is updated to return 404 if no pacakges is found. the changes is in the same branch "add-publish-api-new" of commit 1bfc8c57
